/*Generated by Lix*/
:- dynamic flag/2, memo_table/2.
:- use_module(library(lists)).
:- use_module(library(terms)).
:- op(1150, fx, type).
/*app__1(_6593,_6595)=app(_6593,'.'(b,[]),_6595)*/
app__1([], [b]).
app__1([A|B], [A|C]) :-
        app__1(B, C).
app([a,b,c,d], [b], A) :-
        app__1([a,b,c,d], A).
