/*Generated by Lix*/
:- dynamic flag/2, memo_table/2.
:- use_module(library(lists)).
:- use_module(library(terms)).
:- op(1150, fx, type).
/*test__1(_6321)=test(_6321)*/
test__1(A) :-
        (   a=A
        ;   b=A
        ).
test(A) :-
        test__1(A).
